version: 2

models:
  - name: gh_issues
    config: 
      contract:
        enforced: true
    columns:
      - name: id
        data_type: bigint
        constraints:
          - type: primary_key
      - name: assignee
        data_type: TEXT
      - name: author
        data_type: TEXT
      - name: stage
        data_type: TEXT
      - name: issue_url
        data_type: TEXT
      - name: title
        data_type: TEXT
      - name: repository
        data_type: TEXT
      - name:  issue_number
        data_type: bigint
      - name: labels
        data_type: JSONB
      - name: closed_at
        data_type: TIMESTAMP WITH TIME ZONE
      - name: created_at
        data_type: TIMESTAMP WITH TIME ZONE
  - name: gh_issue_labels
    config: 
      contract:
        enforced: true
    columns:
      - name: id
        data_type: BIGINT
      - name: issue_id
        data_type: BIGINT
        constraints:
          - type: foreign_key
            expression: gh_issues (id)
      - name: color
        data_type: TEXT
      - name: '"default"'
        data_type: TEXT
      - name: description
        data_type: TEXT
      - name: name
        data_type: TEXT
      - name: node_id
        data_type: TEXT
      - name: url
        data_type: TEXT
